"""initial schema

Revision ID: bfe6601a91ca
Revises:
Create Date: 2026-05-31 20:40:16.289894

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bfe6601a91ca"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "students", "first_name", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.alter_column(
        "students", "last_name", existing_type=sa.VARCHAR(length=50), nullable=False
    )
    op.alter_column("students", "age", existing_type=sa.INTEGER(), nullable=False)
    op.alter_column("students", "score", existing_type=sa.INTEGER(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("students", "score", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column("students", "age", existing_type=sa.INTEGER(), nullable=True)
    op.alter_column(
        "students", "last_name", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    op.alter_column(
        "students", "first_name", existing_type=sa.VARCHAR(length=50), nullable=True
    )
    # ### end Alembic commands ###
