name: Setup uv
description: Install project dependencies using uv

runs:
  using: composite

  steps:
    - uses: astral-sh/setup-uv@v5
      with:
        enable-cached: true

    - name: Install dependencies
      shell: bash
      run: uv sync --frozen --dev